Repository PI-coffeeBreak/core, pull requests merged in 2025-03, with the labels that each got.

#10 Scrum 97 app custom pages api schemas
  main.py
  models/ui/page.py
  routes/ui/page.py
  schemas/ui/page.py
Labels: enhancement

#12 Event Bus Complete.
  models/event.py
  schemas/event.py
  services/event_bus.py
  tests/test_event_bus.py
  tests/test_singleton_event_bus.py
Labels: enhancement

#13 Fix/add cors header
  main.py
Labels: bug

#15 check role in all user endpoints
  routes/users.py
Labels: fix

#16 fix plugin settings router
  main.py
  routes/ui/plugin_settings.py
  services/ui/plugin_settings.py
Labels: fix

#17 add api/v1 to redirect to all routes
  main.py
  routes/__init__.py
Labels: fix

#18 add 'batch' endpoint to post list of activities
  routes/activities.py
Labels: fix

#19 fixed
  dependencies/app.py
Labels: fix

#21 add color_theme model, schema, and routes
  main.py
  models/ui/color_theme.py
  routes/__init__.py
  routes/ui/color_themes.py
  schemas/ui/color_theme.py
Labels: enhancement

#23 roles and role users endpoint
  routes/users.py
  services/user_service.py
Labels: enhancement

#29 fix plugin loader
  plugin_loader.py
Labels: fix

#26 create page service and refactor
  routes/ui/page.py
  services/ui/page_service.py
Labels: enhancement

#30 unload plugins when closing
  main.py
  plugin_loader.py
Labels: fix
