Repository PI-coffeeBreak/core, pull requests merged in 2025-04, with the labels that each got.

#33 only list roles with coffeebreak prefix
  services/user_service.py
Labels: fix

#42 Invalid Mongo _id does not break code
  routes/ui/page.py
  services/ui/page_service.py
  utils/mongoserializer.py
Labels: bug, fix

#48 Scrum 163 create backend default components
  defaults.py
  schemas/ui/color.py
  schemas/ui/components/button.py
  schemas/ui/components/image.py
  schemas/ui/components/text.py
  schemas/ui/components/title.py
Labels: enhancement

#49 Fix/component names
  defaults.py
  schemas/ui/components/button.py
  schemas/ui/components/image.py
  schemas/ui/components/text.py
  schemas/ui/components/title.py
Labels: enhancement

#52 Scrum 172 event data api endpoints
  .gitignore
  constants/errors.py
  defaults.py
  models/event_info.py
  routes/__init__.py
  routes/event_info.py
  routes/ui/page.py
  schemas/event_info.py
  schemas/ui/page.py
Labels: enhancement

#55 First time event creation complete
  dependencies/auth.py
  routes/event_info.py
  schemas/event_info.py
  services/user_service.py
Labels: enhancement

#56 Require AUth added
  schemas/ui/page.py
Labels: enhancement

#57 Media Service Comments
  services/media.py
Labels: documentation

#61 Scrum 177 component with event location link
  defaults.py
  schemas/ui/components/location.py
Labels: enhancement

#66 Scrum 209 create video component
  defaults.py
  schemas/ui/components/video.py
Labels: enhancement

#68 Scrum 233 integrate activities with media service for session image upload
  routes/activities.py
  utils/media.py
Labels: enhancement

#64 Only enabled pages being returned and endpoint that returns all.
  routes/ui/page.py
Labels: enhancement
